//створюємо об'єктом, а не строкою

export const ENV_VARS = {
  PORT: 'PORT',
  MONGODB_USER: 'MONGODB_USER',
  MONGODB_PASSWORD: 'MONGODB_PASSWORD',
  MONGODB_DOMAIN: 'MONGODB_DOMAIN',
  MONGODB_DATABASE: 'MONGODB_DATABASE',
  // скидання пароля
  SMTP_HOST: 'SMTP_HOST',
  SMTP_PORT: 'SMTP_PORT',
  SMTP_USER: 'SMTP_USER',
  SMTP_PASS: 'SMTP_PASS',
  SMTP_FROM: 'SMTP_FROM',
  JWT_SECRET: 'JWT_SECRET',

  FRONTEND_DOMAIN: 'FRONTEND_DOMAIN', //адреса куди переправляє лист
  BACKEND_DOMAIN: 'BACKEND_DOMAIN',

  CLOUDINARY_CLOUD_NAME: 'CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',

  SAVE_FILE_STRATEGY: 'SAVE_FILE_STRATEGY',

  //  Google OAuth
  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET',
  GOOGLE_REDIRECT_URI: 'GOOGLE_REDIRECT_URI',
};
